/// Generated by `tool/env_apply.sh` / `dart run tool/bump_version.dart`. Do not edit by hand.
abstract final class AppVersion {
  static const String name = '1.3.0';
  static const int build = 6;
  static const String full = '$name+$build';
}
