/// Generated by `dart run tool/bump_version.dart`. Do not edit by hand.
abstract final class AppVersion {
  static const String name = '1.1.0';
  static const int build = 2;
  static const String full = '$name+$build';
}
