# Generated by Django 5.1.15 on 2026-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='debug_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
