import 'dart:io';

import 'package:nasyad/core/version/semver.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/bump_version.dart <major|minor|patch>',
    );
    exitCode = 64;
    return;
  }

  final kind = parseBumpKind(args.first);
  if (kind == null) {
    stderr.writeln('Unknown bump kind: ${args.first}');
    stderr.writeln('Use: major | minor | patch');
    exitCode = 64;
    return;
  }

  final root = _findPackageRoot();
  final pubspecFile = File('${root.path}/pubspec.yaml');
  final versionFile = File('${root.path}/lib/core/version/app_version.dart');

  final pubspec = pubspecFile.readAsStringSync();
  final match = RegExp(
    r'^version:\s*(\d+\.\d+\.\d+(?:\+\d+)?)\s*$',
    multiLine: true,
  ).firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not find version: line in pubspec.yaml');
    exitCode = 1;
    return;
  }

  final current = SemVer.parse(match.group(1)!);
  final next = current.bump(kind);

  pubspecFile.writeAsStringSync(
    pubspec.replaceFirst(match.group(0)!, 'version: ${next.full}'),
  );
  versionFile.writeAsStringSync(_versionDart(next));

  stdout.writeln('Bumped ${current.full} → ${next.full}');
  stdout.writeln(
    'Add/update changelog notes for ${next.name} in '
    'lib/core/version/app_changelog.dart',
  );
}

Directory _findPackageRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not find pubspec.yaml from ${Directory.current.path}',
      );
    }
    dir = parent;
  }
}

String _versionDart(SemVer version) {
  return '''
/// Generated by `dart run tool/bump_version.dart`. Do not edit by hand.
abstract final class AppVersion {
  static const String name = '${version.name}';
  static const int build = ${version.build};
  static const String full = '\$name+\$build';
}
''';
}
