#!/usr/bin/env bash
# Start local Supabase, apply migrations, write Flutter dart-defines for this machine.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v supabase >/dev/null 2>&1; then
  echo "Supabase CLI not found. Install: https://supabase.com/docs/guides/local-development/cli/getting-started" >&2
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo "Docker is not running. Start Docker Desktop / dockerd first." >&2
  exit 1
fi

echo "Starting local Supabase stack..."
supabase start

echo "Applying migrations..."
supabase db reset --yes

API_URL="$(supabase status -o json | python3 -c "import json,sys; print(json.load(sys.stdin)['API_URL'])")"
ANON_KEY="$(supabase status -o json | python3 -c "import json,sys; print(json.load(sys.stdin)['ANON_KEY'])")"

LOCAL_ENV="$ROOT/tool/supabase_env.local.sh"
cat >"$LOCAL_ENV" <<EOF
# Generated by tool/configure_supabase_local.sh — do not commit.
export SUPABASE_URL='$API_URL'
export SUPABASE_ANON_KEY='$ANON_KEY'
EOF
chmod 600 "$LOCAL_ENV"

DART_DEFINES="$ROOT/supabase/dart_defines.local.json"
python3 - <<PY
import json
from pathlib import Path
Path("$DART_DEFINES").write_text(json.dumps({
    "SUPABASE_URL": "$API_URL",
    "SUPABASE_ANON_KEY": "$ANON_KEY",
}, indent=2) + "\n")
PY
chmod 600 "$DART_DEFINES"

echo ""
echo "Local Supabase is ready."
echo "  Studio:  $(supabase status -o json | python3 -c "import json,sys; print(json.load(sys.stdin)['STUDIO_URL'])")"
echo "  API:     $API_URL"
echo ""
echo "Run the app with sync enabled:"
echo "  source tool/supabase_env.local.sh"
echo "  flutter run --dart-define=SUPABASE_URL=\$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=\$SUPABASE_ANON_KEY"
echo ""
echo "Or:"
echo "  flutter run --dart-define-from-file=supabase/dart_defines.local.json"
