#!/usr/bin/env bash
# Apply repo-root `.env/` into tracked/local runtime files.
# Syncs version → client pubspec + AppVersion + server OpenAPI VERSION,
# and materializes Android local properties + signing files.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="$ROOT/.env"
EXAMPLE_DIR="$ROOT/env.example"
CLIENT_ANDROID="$ROOT/client/android"

log() { echo "==> $*"; }
die() { echo "env_apply: $*" >&2; exit 1; }

ensure_env_dir() {
  if [[ -d "$ENV_DIR" && -f "$ENV_DIR/app.env" ]]; then
    return 0
  fi
  if [[ ! -d "$EXAMPLE_DIR" ]]; then
    die "missing $EXAMPLE_DIR"
  fi
  mkdir -p "$ENV_DIR"
  cp -a "$EXAMPLE_DIR/app.env" "$ENV_DIR/app.env"
  cp -a "$EXAMPLE_DIR/server.env" "$ENV_DIR/server.env"
  mkdir -p "$ENV_DIR/android"
  if [[ -f "$EXAMPLE_DIR/android/key.properties.example" ]]; then
    cp -a "$EXAMPLE_DIR/android/key.properties.example" \
      "$ENV_DIR/android/key.properties.example"
  fi
  log "created .env/ from env.example/ — edit secrets under .env/"
}

# Load KEY=VALUE files (comments/blanks ok).
load_env_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  set -a
  # shellcheck disable=SC1090
  source "$file"
  set +a
}

read_env_value() {
  local file="$1" key="$2" default="${3:-}"
  if [[ -f "$file" ]]; then
    local line
    line="$(grep -E "^${key}=" "$file" | tail -n1 || true)"
    if [[ -n "$line" ]]; then
      echo "${line#*=}"
      return 0
    fi
  fi
  echo "$default"
}

sync_version() {
  local version build full
  version="$(read_env_value "$ENV_DIR/app.env" APP_VERSION "1.0.0")"
  build="$(read_env_value "$ENV_DIR/app.env" APP_BUILD "1")"
  full="${version}+${build}"

  local pubspec="$ROOT/client/pubspec.yaml"
  local version_dart="$ROOT/client/lib/core/version/app_version.dart"
  local settings="$ROOT/server/config/settings.py"

  if [[ -f "$pubspec" ]]; then
    if grep -qE '^version:' "$pubspec"; then
      sed -i -E "s/^version:[[:space:]]*.*/version: ${full}/" "$pubspec"
    else
      die "no version: line in client/pubspec.yaml"
    fi
  fi

  cat >"$version_dart" <<EOF
/// Generated by \`tool/env_apply.sh\` / \`dart run tool/bump_version.dart\`. Do not edit by hand.
abstract final class AppVersion {
  static const String name = '${version}';
  static const int build = ${build};
  static const String full = '\$name+\$build';
}
EOF

  if [[ -f "$settings" ]]; then
    if grep -qE '"VERSION"[[:space:]]*:' "$settings"; then
      sed -i -E "s/(\"VERSION\"[[:space:]]*:[[:space:]]*\")([0-9]+\.[0-9]+\.[0-9]+)(\")/\1${version}\3/" \
        "$settings"
    fi
  fi

  log "version synced: ${full}"
}

materialize_android() {
  local app_id mode
  app_id="$(read_env_value "$ENV_DIR/app.env" APP_APPLICATION_ID "com.example.nasyad")"
  mode="$(read_env_value "$ENV_DIR/app.env" NASYAD_MODE "debug")"

  mkdir -p "$CLIENT_ANDROID"

  cat >"$CLIENT_ANDROID/nasyad.local.properties" <<EOF
# Generated by tool/env_apply.sh from .env/ — do not commit.
applicationId=${app_id}
EOF

  local src_props="$ENV_DIR/android/key.properties"
  local src_jks="$ENV_DIR/android/nasyad-release.jks"
  local dest_props="$CLIENT_ANDROID/key.properties"
  local dest_keystore_dir="$CLIENT_ANDROID/keystore"
  local dest_jks="$dest_keystore_dir/nasyad-release.jks"

  if [[ -f "$src_props" ]]; then
    mkdir -p "$dest_keystore_dir"
    # Rewrite storeFile to keystore/nasyad-release.jks under client/android/
    {
      grep -vE '^(storeFile)=' "$src_props" || true
      echo "storeFile=keystore/nasyad-release.jks"
    } >"$dest_props"
    if [[ -f "$src_jks" ]]; then
      cp -a "$src_jks" "$dest_jks"
    elif [[ -f "$CLIENT_ANDROID/keystore/nasyad-release.jks" ]]; then
      : # already present
    fi
    log "android signing material applied from .env/android/"
  else
    rm -f "$dest_props"
    if [[ "$mode" == "release" ]]; then
      die "NASYAD_MODE=release requires .env/android/key.properties and keystore"
    fi
    log "no .env/android/key.properties — release builds will use debug signing"
  fi

  if [[ "$mode" == "release" ]]; then
    [[ -f "$dest_props" ]] || die "release mode needs key.properties"
    [[ -f "$dest_jks" || -f "$src_jks" ]] || die "release mode needs nasyad-release.jks"
  fi
}

ensure_env_dir
load_env_file "$ENV_DIR/app.env"
load_env_file "$ENV_DIR/server.env"

# NASYAD_MODE drives DJANGO_DEBUG when not explicitly fighting it for apply checks
mode="$(read_env_value "$ENV_DIR/app.env" NASYAD_MODE "debug")"
if [[ "$mode" == "release" ]]; then
  export DJANGO_DEBUG="${DJANGO_DEBUG:-false}"
else
  export DJANGO_DEBUG="${DJANGO_DEBUG:-true}"
fi

sync_version
materialize_android
log "env_apply OK (mode=${mode})"
