# Generated by Django 5.1.15 on 2026-08-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_preset', models.CharField(blank=True, choices=[('generic', 'generic'), ('car', 'car'), ('hvac', 'hvac'), ('appliance', 'appliance'), ('electronics', 'electronics'), ('plumbing', 'plumbing')], max_length=32, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='active', max_length=16)),
                ('usage_unit', models.CharField(blank=True, choices=[('km', 'km'), ('hours', 'hours'), ('cycles', 'cycles')], max_length=16, null=True)),
                ('current_usage', models.PositiveIntegerField(default=0)),
                ('schedule_type', models.CharField(blank=True, choices=[('calendarInterval', 'calendarInterval'), ('usageInterval', 'usageInterval'), ('fixedDate', 'fixedDate')], max_length=32, null=True)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('km', 'km'), ('hours', 'hours'), ('cycles', 'cycles')], max_length=16, null=True)),
                ('fixed_due_at', models.DateTimeField(blank=True, null=True)),
                ('last_maintained_at', models.DateTimeField(blank=True, null=True)),
                ('usage_at_last_maintenance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updated_at'], name='devices_dev_user_id_a69ea0_idx'), models.Index(fields=['user', 'parent_id'], name='devices_dev_user_id_062831_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=36)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('maintenanceDone', 'maintenanceDone'), ('usageUpdate', 'usageUpdate')], max_length=32)),
                ('usage_value', models.IntegerField(blank=True, null=True)),
                ('usage_unit', models.CharField(blank=True, choices=[('km', 'km'), ('hours', 'hours'), ('cycles', 'cycles')], max_length=16, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=16, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='devices_dev_user_id_3579c6_idx'), models.Index(fields=['user', 'device_id'], name='devices_dev_user_id_48473a_idx')],
            },
        ),
    ]
