import 'dart:io';

import 'package:nasyad/core/version/semver.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/bump_version.dart <major|minor|patch>',
    );
    exitCode = 64;
    return;
  }

  final kind = parseBumpKind(args.first);
  if (kind == null) {
    stderr.writeln('Unknown bump kind: ${args.first}');
    stderr.writeln('Use: major | minor | patch');
    exitCode = 64;
    return;
  }

  final packageRoot = _findPackageRoot();
  final repoRoot = _findRepoRoot(packageRoot);
  final pubspecFile = File('${packageRoot.path}/pubspec.yaml');
  final versionFile = File(
    '${packageRoot.path}/lib/core/version/app_version.dart',
  );
  final settingsFile = File('${repoRoot.path}/server/config/settings.py');

  final pubspec = pubspecFile.readAsStringSync();
  final match = RegExp(
    r'^version:\s*(\d+\.\d+\.\d+(?:\+\d+)?)\s*$',
    multiLine: true,
  ).firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not find version: line in pubspec.yaml');
    exitCode = 1;
    return;
  }

  final current = SemVer.parse(match.group(1)!);
  final next = current.bump(kind);

  pubspecFile.writeAsStringSync(
    pubspec.replaceFirst(match.group(0)!, 'version: ${next.full}'),
  );
  versionFile.writeAsStringSync(_versionDart(next));

  if (settingsFile.existsSync()) {
    final settings = settingsFile.readAsStringSync();
    final versionMatch = RegExp(
      r'("VERSION"\s*:\s*")(\d+\.\d+\.\d+)(")',
    ).firstMatch(settings);
    if (versionMatch == null) {
      stderr.writeln(
        'Warning: could not update SPECTACULAR VERSION in '
        'server/config/settings.py — set it to ${next.name} manually.',
      );
    } else {
      settingsFile.writeAsStringSync(
        settings.replaceFirst(
          versionMatch.group(0)!,
          '${versionMatch.group(1)}${next.name}${versionMatch.group(3)}',
        ),
      );
    }
  }

  final notesPath = 'docs/domain/releases/v${next.name}.md';
  final notesFile = File('${repoRoot.path}/$notesPath');
  if (!notesFile.existsSync()) {
    stdout.writeln(
      'Create $notesPath with Client + Server end-user sections '
      '(CI uses it as the GitHub Release body).',
    );
  }

  final appEnv = File('${repoRoot.path}/.env/app.env');
  if (appEnv.existsSync()) {
    var text = appEnv.readAsStringSync();
    text = text.replaceFirstMapped(
      RegExp(r'^APP_VERSION=.*$', multiLine: true),
      (_) => 'APP_VERSION=${next.name}',
    );
    text = text.replaceFirstMapped(
      RegExp(r'^APP_BUILD=.*$', multiLine: true),
      (_) => 'APP_BUILD=${next.build}',
    );
    if (!text.contains(RegExp(r'^APP_VERSION=', multiLine: true))) {
      text = '${text.trimRight()}\nAPP_VERSION=${next.name}\n';
    }
    if (!text.contains(RegExp(r'^APP_BUILD=', multiLine: true))) {
      text = '${text.trimRight()}\nAPP_BUILD=${next.build}\n';
    }
    appEnv.writeAsStringSync(text);
    stdout.writeln('Updated .env/app.env APP_VERSION / APP_BUILD');
  }

  stdout.writeln('Bumped ${current.full} → ${next.full}');
  stdout.writeln(
    'Add/update changelog notes for ${next.name} in '
    'lib/core/version/app_changelog.dart',
  );
  stdout.writeln('Server OpenAPI VERSION set to ${next.name}');
}

Directory _findPackageRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not find pubspec.yaml from ${Directory.current.path}',
      );
    }
    dir = parent;
  }
}

Directory _findRepoRoot(Directory packageRoot) {
  if (packageRoot.path.endsWith('${Platform.pathSeparator}client') ||
      packageRoot.path.endsWith('/client')) {
    return packageRoot.parent;
  }
  if (Directory('${packageRoot.path}/server').existsSync() &&
      Directory('${packageRoot.path}/client').existsSync()) {
    return packageRoot;
  }
  final parent = packageRoot.parent;
  if (Directory('${parent.path}/server').existsSync()) return parent;
  return packageRoot;
}

String _versionDart(SemVer version) {
  return '''
/// Generated by `dart run tool/bump_version.dart`. Do not edit by hand.
abstract final class AppVersion {
  static const String name = '${version.name}';
  static const int build = ${version.build};
  static const String full = '\$name+\$build';
}
''';
}
