# Generated by Django 5.1.15 on 2026-08-07 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable snake_case flag id (e.g. example_remote_flag).', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False, help_text='Kill switch: false evaluates to false for everyone.')),
                ('rollout_percent', models.PositiveSmallIntegerField(default=0, help_text='0–100; sticky cohort when authenticated.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
