// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXRz7hpHrqHM7gvf1mQW528IlqDi8rrs',
    appId: '1:686985039261:web:0c091262f8cb8adfab7374',
    messagingSenderId: '686985039261',
    projectId: 'nasyad-cf73f',
    authDomain: 'nasyad-cf73f.firebaseapp.com',
    storageBucket: 'nasyad-cf73f.firebasestorage.app',
    measurementId: 'G-0MLKG5FDDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClG8NuAmNyLejXbN7LmsPEYcAgZYaxLyE',
    appId: '1:686985039261:android:01925f2798062745ab7374',
    messagingSenderId: '686985039261',
    projectId: 'nasyad-cf73f',
    storageBucket: 'nasyad-cf73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNOuGEepdxK79wfIxQrugd1dqoPdjw0Sg',
    appId: '1:686985039261:ios:80a712cd0d509e81ab7374',
    messagingSenderId: '686985039261',
    projectId: 'nasyad-cf73f',
    storageBucket: 'nasyad-cf73f.firebasestorage.app',
    iosBundleId: 'amini.apps.nasyad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNOuGEepdxK79wfIxQrugd1dqoPdjw0Sg',
    appId: '1:686985039261:ios:80a712cd0d509e81ab7374',
    messagingSenderId: '686985039261',
    projectId: 'nasyad-cf73f',
    storageBucket: 'nasyad-cf73f.firebasestorage.app',
    iosBundleId: 'amini.apps.nasyad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXRz7hpHrqHM7gvf1mQW528IlqDi8rrs',
    appId: '1:686985039261:web:461407b33a903d51ab7374',
    messagingSenderId: '686985039261',
    projectId: 'nasyad-cf73f',
    authDomain: 'nasyad-cf73f.firebaseapp.com',
    storageBucket: 'nasyad-cf73f.firebasestorage.app',
    measurementId: 'G-JH53QS27RR',
  );
}
